name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      working-directory: moonshot

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 작성
      run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yaml
      working-directory: ${{ env.working-directory }}

    - name: build
      run: |
          chmod +x gradlew
          ./gradlew clean build
      working-directory: ${{ env.working-directory }}
      shell: bash
